name: Build CV
on: push

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build CV
        run: nix build

      - name: Upload PDF to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: result/resume.pdf
          tag: latest
          overwrite: true
